[project]
name = "jankai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "openai==2.44.0",
    "python-dotenv==1.1.0",
]

[project.scripts]
jankai = "main:cli_entry"

[tool.setuptools]
packages = ["functions"]

py-modules = ["main", "call_function", "config", "prompts"]
